// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320035332_AddStockAndUpdateProduct")]
    partial class AddStockAndUpdateProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "P001",
                            Name = "MacBook Pro 16\"",
                            Price = 89900m
                        },
                        new
                        {
                            Id = 2,
                            Code = "P002",
                            Name = "iPhone 15 Pro",
                            Price = 42900m
                        },
                        new
                        {
                            Id = 3,
                            Code = "P003",
                            Name = "iPad Air",
                            Price = 21900m
                        },
                        new
                        {
                            Id = 4,
                            Code = "P004",
                            Name = "AirPods Pro",
                            Price = 9900m
                        },
                        new
                        {
                            Id = 5,
                            Code = "P005",
                            Name = "Apple Watch Series 9",
                            Price = 15900m
                        },
                        new
                        {
                            Id = 6,
                            Code = "P006",
                            Name = "Magic Keyboard",
                            Price = 4900m
                        },
                        new
                        {
                            Id = 7,
                            Code = "P007",
                            Name = "Magic Mouse",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 8,
                            Code = "P008",
                            Name = "USB-C Hub 7-in-1",
                            Price = 1290m
                        });
                });

            modelBuilder.Entity("backend.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("backend.Models.Stock", b =>
                {
                    b.HasOne("backend.Models.Product", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("backend.Models.Stock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
